// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxcK_zpG9g2PgbRlHswq60bSYESq7RrM',
    appId: '1:218329869218:web:2f2d7cb9483b7d47e060fb',
    messagingSenderId: '218329869218',
    projectId: 'smart-school-17cbb',
    authDomain: 'smart-school-17cbb.firebaseapp.com',
    storageBucket: 'smart-school-17cbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFhThggyo9ONnZxqOwjoOAdSHsZ8-o0g8',
    appId: '1:218329869218:android:cf491187bbc11cdbe060fb',
    messagingSenderId: '218329869218',
    projectId: 'smart-school-17cbb',
    storageBucket: 'smart-school-17cbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQkt1VsR-_HofcX46yDL60-jLYHk2x4po',
    appId: '1:218329869218:ios:470cc76ff2c993ebe060fb',
    messagingSenderId: '218329869218',
    projectId: 'smart-school-17cbb',
    storageBucket: 'smart-school-17cbb.appspot.com',
    iosBundleId: 'com.example.smartSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQkt1VsR-_HofcX46yDL60-jLYHk2x4po',
    appId: '1:218329869218:ios:470cc76ff2c993ebe060fb',
    messagingSenderId: '218329869218',
    projectId: 'smart-school-17cbb',
    storageBucket: 'smart-school-17cbb.appspot.com',
    iosBundleId: 'com.example.smartSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbxcK_zpG9g2PgbRlHswq60bSYESq7RrM',
    appId: '1:218329869218:web:d699d8b544e03dd7e060fb',
    messagingSenderId: '218329869218',
    projectId: 'smart-school-17cbb',
    authDomain: 'smart-school-17cbb.firebaseapp.com',
    storageBucket: 'smart-school-17cbb.appspot.com',
  );
}
